//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionGaleria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pintor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Pintor()
        {
            this.Tbl_Pintura = new HashSet<Tbl_Pintura>();
        }
    
        public int Id_Pintor { get; set; }
        public int Id_Persona { get; set; }
    
        public virtual Tbl_Persona Tbl_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Pintura> Tbl_Pintura { get; set; }
    }
}
