//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionGaleria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pintura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Pintura()
        {
            this.Tbl_PinturaGenero = new HashSet<Tbl_PinturaGenero>();
        }
    
        public int Id_Pintura { get; set; }
        public Nullable<int> Id_Pintor { get; set; }
        public int Id_Dueno { get; set; }
        public string NombrePintura { get; set; }
        public string Tamano { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual Tbl_Dueno Tbl_Dueno { get; set; }
        public virtual Tbl_Pintor Tbl_Pintor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PinturaGenero> Tbl_PinturaGenero { get; set; }
    }
}
