//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionGaleria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPintura
    {
        public int Id_Pintura { get; set; }
        public string Pintura { get; set; }
        public string Pintor { get; set; }
        public string Dueño { get; set; }
    }
}
