//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionGaleria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPintor
    {
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Nacionalidad { get; set; }
    }
}
